### ISSUE TITLE
Scoped dependencies are not treated as externals

### ISSUE THREAD

**Issue by diffcunha** [halt-hammerzeit/universal-webpack#65]
The `is_external` function is returning `false` if the request is a scoped dependency.

as example, if request is `@scoped/somedep/lib/index`
```js
// server configurations.js
let package_name = request
if (package_name.indexOf('/') >= 0)
{
    package_name = package_name.substring(0, package_name.indexOf('/'))
}
```
`package_name` will be `@scoped` rather than `@scoped/somedep` and it will fail in:
```js
validate_npm_package_path(package_name).validForNewPackages
```

**Comment by halt-hammerzeit** [comment]
hmm, almost never heard of scoped packages before.
ok, I'll test a workaround, maybe tomorrow.

**Comment by halt-hammerzeit** [comment]
Try the new version

**Comment by ronderksen** [comment]
Why is universal webpack determining the external packages? We have several packages (React components) that need to be packaged at build time of the consuming app, so that it all works correctly with the CSS. I have a webpack configuration that determines which files are external and which are not. I did not expect universal-webpack to ignore and override this.

For now, I've fixed the version of universal webpack to 0.3.3, but I hope there is a way to get around this issue.

**Comment by halt-hammerzeit** [comment]
Yes, it's not bundling external packages as part of the server-side build because they're all available in `node_modules`.
Otherwise a developer can use `exclude_from_externals` option to make certain dependencies not external and bundle them on server side.

**Comment by ronderksen** [comment]
@halt-hammerzeit Thanks, adding a regex to `exclude_from_externals` fixed the issue!
